/*
 * Yandex Lavka
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package controllers

import (
	"net/http"
	"yandex-team.ru/lavka/core"
	"yandex-team.ru/lavka/models"

	"github.com/gin-gonic/gin"
)

// CompleteOrder -
func CompleteOrder(c *gin.Context) {
	var completeOrderRequest models.CompleteOrderRequestDto
	if err := c.BindJSON(&completeOrderRequest); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{})
	}

	orders, err := core.CompleteOrder(completeOrderRequest)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{})
	}
	c.JSON(http.StatusOK, orders)
}

// CreateOrder -
func CreateOrder(c *gin.Context) {
	var createOrderRequest models.CreateOrderRequest
	if err := c.BindJSON(&createOrderRequest); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{})
	}

	orders, err := core.CreateOrder(createOrderRequest)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{})
	}

	c.JSON(http.StatusOK, orders)
}

// GetOrder -
func GetOrder(c *gin.Context) {
	orderId := c.Param("order_id")
	order, err := core.GetOrder(orderId)

	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{})
	}

	c.JSON(http.StatusOK, order)
}

// GetOrders -
func GetOrders(c *gin.Context) {
	orders, err := core.GetOrders(c.Query("offset"), c.Query("limit"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{})
	}
	c.JSON(http.StatusOK, orders)
}

// OrdersAssign - Распределение заказов по курьерам.
func OrdersAssign(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
