/*
 * Yandex Lavka
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type CreateCourierDto struct {
	CourierType string `json:"courier_type"`

	Regions []int32 `json:"regions"`

	WorkingHours []string `json:"working_hours"`
}
