/*
 * Yandex Lavka
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type GetCouriersResponse struct {
	Couriers []CourierDto `json:"couriers"`

	Limit int32 `json:"limit"`

	Offset int32 `json:"offset"`
}
