/*
 * Yandex Lavka
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type GetCourierMetaInfoResponse struct {
	CourierId int64 `json:"courier_id"`

	CourierType string `json:"courier_type"`

	Regions []int32 `json:"regions"`

	WorkingHours []string `json:"working_hours"`

	Rating int32 `json:"rating,omitempty"`

	Earnings int32 `json:"earnings,omitempty"`
}
