/*
 * Yandex Lavka
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type CourierDto struct {
	CourierId int64 `json:"courier_id" gorm:"primaryKey"`

	CourierType string `json:"courier_type"`

	Regions []int32 `json:"regions" gorm:"type:integer[]"`

	WorkingHours []string `json:"working_hours" gorm:"type:text[]"`
}
